CREATE TABLE administrador (
 cpf VARCHAR(11) PRIMARY KEY,
 nm_adm VARCHAR(255) NOT NULL,
 email VARCHAR(255) NOT NULL UNIQUE,
 senha VARCHAR(10) NOT NULL,
 status VARCHAR(20) NOT NULL CHECK (status IN ('ATIVO', 'INATIVO', 'BLOQUEADO'))
);
